#!/bin/bash

pcurl() {
	username="$(whoami)"
	echo -n "Password: " 1>&2
	read -s password 1>&2
	curl -u $username:$password "$@"
}

function run_temp_env(){
	export HISTFILE="/dev/null"
	$shell
	exit
}

function download_as_chrome(){
	wget -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' "$@"
}
