#!/bin/bash

which git 1> /dev/null 2> /dev/null
G_EXIST=$?
if [[ 0 != $G_EXIST ]]; then
	# Git isn't installed
	echo "git not found. Please install git for display of git branch in prompt"
else
	# Git is installed
	function parse_git_branch(){
		git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
	}
	
	alias g='git'
	alias gsha="git rev-parse HEAD" #Show sha of last commit
	source /usr/share/bash-completion/completions/git
	complete -o bashdefault -o default -o nospace -F __git_wrap__git_main g
fi
